export const HAIP_EVENT_TYPES = [
  "HAI",
  "PING",
  "PONG",
  "ERROR",
  "FLOW_UPDATE",
  "TRANSACTION_START",
  "TRANSACTION_END",
  // MAYBE GET RID OF?
  "RUN_STARTED",
  "RUN_FINISHED",
  "RUN_CANCEL",
  "RUN_ERROR",
  "REPLAY_REQUEST",
  "TEXT_MESSAGE_START",
  "TEXT_MESSAGE_PART",
  "TEXT_MESSAGE_END",
  "AUDIO_CHUNK",
  "TOOL_CALL",
  "TOOL_UPDATE",
  "TOOL_DONE",
  "TOOL_CANCEL",
  "TOOL_LIST",
  "TOOL_SCHEMA",
  "PAUSE_CHANNEL",
  "RESUME_CHANNEL"
] as const;

export type HAIPEventType = typeof HAIP_EVENT_TYPES[number];